[versions]
agp = "8.8.2"
fmsdk = "0.1.1.2"
authsdk = "0.0.6.7"
cardssdk = "0.1.0.0"

kotlin = "2.1.10"
coreKtx = "1.15.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
appcompat = "1.7.0"
material = "1.12.0"
navigationFragmentKtx = "2.8.8"

[libraries]
fm-sdk = { module = "com.mcards.sdk:fm", version.ref = "fmsdk" }
auth-sdk = { module = "com.mcards.sdk:auth", version.ref = "authsdk" }
cards-sdk = { module = "com.mcards.sdk:cards", version.ref = "cardssdk" }

androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-navigation-fragment-ktx = { group = "androidx.navigation", name = "navigation-fragment-ktx", version.ref = "navigationFragmentKtx" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }

